---
- name: Enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: All nodes - Inbound rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 2376/tcp
    - 8472/udp
    - 10250/tcp

- name: Etcd nodes - Inbound rules
  firewalld:
    port: 2379-2380/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'etcd' in hostvars[inventory_hostname]['rke_role']"

- name: Controlplane nodes - Inbound rules
  firewalld:
    port: 6443/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "'controlplane' in hostvars[inventory_hostname]['rke_role']"

- name: Controlplane nodes and worker nodes - Inbound rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: "'controlplane' in hostvars[inventory_hostname]['rke_role'] or 'worker' in hostvars[inventory_hostname]['rke_role']"
  loop:
    - 30000-32767/tcp
    - 80/tcp
    - 443/tcp
