# This is a basic workflow to help you get started with Actions

name: Ansible Galaxy

on:
  push:
    branches:
      - devel
      - master
      - release/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./"
        
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Publish
        uses: robertdebock/galaxy-action@master
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
